### ISSUE TITLE
关于文档的疑惑。

### ISSUE THREAD

**Issue by h7ml** [youngjuning/react-dnd#1]
首先很开心有关于react-dnd的中文文档。但是目前刚起步就挂了3个广告。。、且都是邀请制的，很难让人不疑惑是为了让其走邀请而开的这个repo。另外vercel国内被墙，建议绑定域名、

**Comment by zisheng-ai** [comment]
> 首先很开心有关于react-dnd的中文文档。但是目前刚起步就挂了3个广告。。、且都是邀请制的，很难让人不疑惑是为了让其走邀请而开的这个repo。另外vercel国内被墙，建议绑定域名、

首先感谢对项目的关注。

## 关于广告和邀请制

翻译数量和质量都达到之后广告那边才会审核通过。

可以关注下 [紫竹翻译计划](https://youngjuning.js.org/zizhudocs/)，这个计划本身就是寻求一种变现机制来奖励翻译者的。

目前邀请制是有必要的，奖励机制和合作模式都还在探索，鉴于之前几次翻译计划的失败，贸然扩大范围和无偿翻译都很容易失败。

## 关于 域名解析

前端的文档翻译，我会在翻译数量和质量都达标之后申请 js.org 二级域名，一是 js.org  免费，二是 js.org 权重高。

**Comment by zisheng-ai** [comment]
翻译者角度：网站能否通过广告审核取决于网站质量，所以这也是对翻译者的一个鞭策。他们既能在自己感兴趣的领域深入研究原始文档，又能顺便获得经济奖励。
阅读者角度：广告数量位置和数量是严格控制过的，基本不会影响阅读体验。
管理员角度：站在我的角度，方便管理和发放奖励是第一位的。一个网站对应固定的一个或多个翻译者很好分。
